// Code generated by tygo. DO NOT EDIT.
// Re-generate with: cd app && pnpm gen:api-types
//
// This file contains TypeScript types for SiYuan public API endpoint
// request/response parameters, generated from kernel/api/types.go.


//////////
// source: types.go
/*
Package api defines typed request and response structures for SiYuan public API
endpoints. These types serve as the single source of truth for API contracts
between the backend and the frontend.

TypeScript equivalents are auto-generated by tygo — run `cd app && pnpm gen:api-types`
after modifying any struct here.
*/

/**
 * LsNotebooksRequest is the request body for POST /api/notebook/lsNotebooks.
 */
export interface LsNotebooksRequest {
  /**
   * Whether to include flashcard counts for each notebook (default false).
   */
  flashcard: boolean;
}
/**
 * LsNotebooksResponse is the data field in the response from /api/notebook/lsNotebooks.
 */
export interface LsNotebooksResponse {
  notebooks: (ResNotebook | undefined)[];
}
/**
 * ResNotebook represents a notebook in API responses.
 */
export interface ResNotebook {
  id: string;
  name: string;
  icon: string;
  sort: number /* int */;
  sortMode: number /* int */;
  closed: boolean;
  newFlashcardCount: number /* int */;
  dueFlashcardCount: number /* int */;
  flashcardCount: number /* int */;
}
/**
 * OpenNotebookRequest is the request body for POST /api/notebook/openNotebook.
 */
export interface OpenNotebookRequest {
  notebook: string; // Notebook ID
}
/**
 * CloseNotebookRequest is the request body for POST /api/notebook/closeNotebook.
 */
export interface CloseNotebookRequest {
  notebook: string; // Notebook ID
}
/**
 * RenameNotebookRequest is the request body for POST /api/notebook/renameNotebook.
 */
export interface RenameNotebookRequest {
  notebook: string; // Notebook ID
  name: string; // New notebook name
}
/**
 * CreateNotebookRequest is the request body for POST /api/notebook/createNotebook.
 */
export interface CreateNotebookRequest {
  name: string; // New notebook name
}
/**
 * CreateNotebookResponse is the data field in the response from /api/notebook/createNotebook.
 */
export interface CreateNotebookResponse {
  notebook?: ResNotebook;
}
/**
 * RemoveNotebookRequest is the request body for POST /api/notebook/removeNotebook.
 */
export interface RemoveNotebookRequest {
  notebook: string; // Notebook ID
}
/**
 * GetNotebookConfRequest is the request body for POST /api/notebook/getNotebookConf.
 */
export interface GetNotebookConfRequest {
  notebook: string; // Notebook ID
}
/**
 * SetNotebookConfRequest is the request body for POST /api/notebook/setNotebookConf.
 */
export interface SetNotebookConfRequest {
  notebook: string; // Notebook ID
  conf: ResNotebookConfData;
}
/**
 * ResNotebookConfData represents notebook configuration.
 */
export interface ResNotebookConfData {
  name: string;
  icon: string;
  sort: number /* int */;
  sortMode: number /* int */;
  refCreateSaveBox: string;
  refCreateSavePath: string;
  docCreateSaveBox: string;
  docCreateSavePath: string;
  dailyNoteSavePath: string;
  dailyNoteTemplatePath: string;
}
/**
 * CreateDocWithMdRequest is the request body for POST /api/filetree/createDocWithMd.
 */
export interface CreateDocWithMdRequest {
  notebook: string; // Target notebook ID
  path: string; // Document path (e.g. /path/to/doc)
  markdown: string; // Markdown content
  attrs?: { [key: string]: string}; // Optional block attributes
}
/**
 * RenameDocRequest is the request body for POST /api/filetree/renameDoc.
 */
export interface RenameDocRequest {
  notebook: string; // Notebook ID
  path: string; // Document path
  title: string; // New title
}
/**
 * RemoveDocRequest is the request body for POST /api/filetree/removeDoc.
 */
export interface RemoveDocRequest {
  notebook: string; // Notebook ID
  path: string; // Document path
}
/**
 * MoveDocsRequest is the request body for POST /api/filetree/moveDocs.
 */
export interface MoveDocsRequest {
  fromNotebook: string; // Source notebook ID
  fromPaths: string[]; // Source document paths
  toNotebook: string; // Target notebook ID
  toPath: string; // Target parent path
}
/**
 * GetHPathByPathRequest is the request body for POST /api/filetree/getHPathByPath.
 */
export interface GetHPathByPathRequest {
  notebook: string; // Notebook ID
  path: string; // Document path
}
/**
 * GetHPathByIDRequest is the request body for POST /api/filetree/getHPathByID.
 */
export interface GetHPathByIDRequest {
  id: string; // Block ID
}
/**
 * GetPathByIDRequest is the request body for POST /api/filetree/getPathByID.
 */
export interface GetPathByIDRequest {
  id: string; // Block ID
}
/**
 * GetIDsByHPathRequest is the request body for POST /api/filetree/getIDsByHPath.
 */
export interface GetIDsByHPathRequest {
  notebook: string; // Notebook ID
  path: string; // Human-readable path
}
/**
 * TDataType is the type of block data content: Markdown or DOM.
 */
export type TDataType = string; // "markdown" | "dom"
/**
 * InsertBlockRequest is the request body for POST /api/block/insertBlock.
 */
export interface InsertBlockRequest {
  dataType: TDataType; // Content type: "markdown" or "dom"
  data: string; // Content to insert
  nextID?: string; // ID of the block to insert before
  previousID?: string; // ID of the block to insert after
  parentID?: string; // ID of the parent block
}
/**
 * PrependBlockRequest is the request body for POST /api/block/prependBlock.
 */
export interface PrependBlockRequest {
  dataType: TDataType; // Content type: "markdown" or "dom"
  data: string; // Content to prepend
  parentID: string; // ID of the parent block
}
/**
 * AppendBlockRequest is the request body for POST /api/block/appendBlock.
 */
export interface AppendBlockRequest {
  dataType: TDataType; // Content type: "markdown" or "dom"
  data: string; // Content to append
  parentID: string; // ID of the parent block
}
/**
 * UpdateBlockRequest is the request body for POST /api/block/updateBlock.
 */
export interface UpdateBlockRequest {
  id: string; // Block ID
  dataType: TDataType; // Content type: "markdown" or "dom"
  data: string; // New content
}
/**
 * DeleteBlockRequest is the request body for POST /api/block/deleteBlock.
 */
export interface DeleteBlockRequest {
  id: string; // Block ID
}
/**
 * MoveBlockRequest is the request body for POST /api/block/moveBlock.
 */
export interface MoveBlockRequest {
  id: string; // Block ID to move
  previousID?: string; // ID of the block to place after
  parentID?: string; // ID of the parent block to place in
}
/**
 * FoldBlockRequest is the request body for POST /api/block/foldBlock.
 */
export interface FoldBlockRequest {
  id: string; // Block ID
}
/**
 * UnfoldBlockRequest is the request body for POST /api/block/unfoldBlock.
 */
export interface UnfoldBlockRequest {
  id: string; // Block ID
}
/**
 * GetBlockKramdownRequest is the request body for POST /api/block/getBlockKramdown.
 */
export interface GetBlockKramdownRequest {
  id: string; // Block ID
}
/**
 * GetBlockKramdownResponse is the data field in the response from /api/block/getBlockKramdown.
 */
export interface GetBlockKramdownResponse {
  id: string;
  kramdown: string;
}
/**
 * GetChildBlocksRequest is the request body for POST /api/block/getChildBlocks.
 */
export interface GetChildBlocksRequest {
  id: string; // Block ID
}
/**
 * TransferBlockRefRequest is the request body for POST /api/block/transferBlockRef.
 */
export interface TransferBlockRefRequest {
  fromID: string; // Source block ID
  toID: string; // Target block ID
}
/**
 * GetBlockRequest is the request body for POST /api/block/getBlock.
 */
export interface GetBlockRequest {
  id: string; // Block ID
}
/**
 * ResBlock represents a block returned in API responses.
 */
export interface ResBlock {
  box: string;
  path: string;
  hPath: string;
  id: string;
  rootID: string;
  parentID: string;
  name: string;
  alias: string;
  memo: string;
  tag: string;
  content: string;
  fcontent: string;
  markdown: string;
  folded: boolean;
  type: string;
  subType: string;
  ial: { [key: string]: string};
  children: (ResBlock | undefined)[];
  refCount: number /* int */;
  sort: number /* int */;
  created: string;
  updated: string;
}
/**
 * ResChildBlock represents a child block returned by /api/block/getChildBlocks.
 */
export interface ResChildBlock {
  id: string;
  type: string;
  subType?: string;
  content?: string;
  markdown?: string;
}
/**
 * ResOperation represents a transaction operation in API responses.
 */
export interface ResOperation {
  action: string;
  data: any;
  id: string;
  parentID: string;
  previousID: string;
  nextID: string;
  retData: any;
}
/**
 * ResTransaction represents a transaction returned by block write operations.
 */
export interface ResTransaction {
  doOperations: (ResOperation | undefined)[];
  undoOperations: (ResOperation | undefined)[];
}
/**
 * GetBlockAttrsRequest is the request body for POST /api/attr/getBlockAttrs.
 */
export interface GetBlockAttrsRequest {
  id: string; // Block ID
}
/**
 * SetBlockAttrsRequest is the request body for POST /api/attr/setBlockAttrs.
 */
export interface SetBlockAttrsRequest {
  id: string; // Block ID
  attrs: { [key: string]: string}; // Attribute key-value pairs to set (set value to empty string to remove)
}
/**
 * SQLRequest is the request body for POST /api/sql/sql.
 */
export interface SQLRequest {
  stmt: string; // SQL SELECT statement
}
/**
 * RenderTemplateRequest is the request body for POST /api/template/render.
 */
export interface RenderTemplateRequest {
  id: string; // Block ID for template context
  path: string; // Template file path
}
/**
 * RenderSprigRequest is the request body for POST /api/template/renderSprig.
 */
export interface RenderSprigRequest {
  template: string; // Sprig template string
}
/**
 * GetFileRequest is the request body for POST /api/file/getFile.
 */
export interface GetFileRequest {
  path: string; // File path relative to the workspace data directory
}
/**
 * PutFileRequest is the request body for POST /api/file/putFile (multipart form).
 */
export interface PutFileRequest {
  path: string; // File path relative to the workspace data directory
  isDir: boolean; // Whether to create a directory instead of a file
  modTime: number /* int64 */; // Modification time (Unix millisecond timestamp)
}
/**
 * RemoveFileRequest is the request body for POST /api/file/removeFile.
 */
export interface RemoveFileRequest {
  path: string; // File path relative to the workspace data directory
}
/**
 * RenameFileRequest is the request body for POST /api/file/renameFile.
 */
export interface RenameFileRequest {
  path: string; // Current file path
  newPath: string; // New file path
}
/**
 * ListFilesRequest is the request body for POST /api/file/listFiles.
 */
export interface ListFilesRequest {
  path: string; // Directory path relative to the workspace data directory
}
/**
 * ResFile represents a file entry returned by /api/file/listFiles.
 */
export interface ResFile {
  isDir: boolean;
  isSymlink: boolean;
  name: string;
  size: number /* int64 */;
  updated: number /* int64 */; // Unix millisecond timestamp
}
/**
 * ExportMdContentRequest is the request body for POST /api/export/exportMdContent.
 */
export interface ExportMdContentRequest {
  id: string; // Document block ID
}
/**
 * ExportMdContentResponse is the data field in the response from /api/export/exportMdContent.
 */
export interface ExportMdContentResponse {
  hPath: string; // Human-readable path
  content: string; // Markdown content
}
/**
 * PushMessageRequest is the request body for POST /api/notification/pushMsg.
 */
export interface PushMessageRequest {
  msg: string; // Message content
  timeout?: number /* int */; // Display duration in milliseconds (default 7000)
}
/**
 * PushMessageResponse is the data field in the response from /api/notification/pushMsg.
 */
export interface PushMessageResponse {
  id: string; // Message ID (can be used to close the message)
}
/**
 * PushErrMsgRequest is the request body for POST /api/notification/pushErrMsg.
 */
export interface PushErrMsgRequest {
  msg: string; // Error message content
  timeout?: number /* int */; // Display duration in milliseconds (default 7000)
}
/**
 * PushErrMsgResponse is the data field in the response from /api/notification/pushErrMsg.
 */
export interface PushErrMsgResponse {
  id: string; // Message ID
}
/**
 * ForwardProxyRequest is the request body for POST /api/network/forwardProxy.
 */
export interface ForwardProxyRequest {
  url: string; // Target URL
  method: string; // HTTP method
  timeout?: number /* int */; // Timeout in milliseconds
  contentType?: string; // Request content type
  headers?: { [key: string]: string}[]; // Request headers
  payload?: any; // Request body
  payloadEncoding?: string; // Payload encoding: "text", "base64", "base64-std", "base64-url", "base64-raw", "base64-url-raw"
  responseEncoding?: string; // Response encoding: "text", "base64", "base64-std", "base64-url", "base64-raw", "base64-url-raw"
}
/**
 * ForwardProxyResponse is the data field in the response from /api/network/forwardProxy.
 */
export interface ForwardProxyResponse {
  contentType: string; // Response content type
  body: string; // Response body (encoding determined by request's responseEncoding)
  bodyEncoding: string; // Encoding used for body
  headers: { [key: string]: string[]}; // Response headers
  status: string; // HTTP status text
  statusCode: number /* int */; // HTTP status code
}
/**
 * GetConfResponse is the data field in the response from /api/system/getConf.
 * The conf field is defined in kernel/model/conf.go (AppConf).
 */
export interface GetConfResponse {
  /**
   * conf contains the full application configuration.
   * The TypeScript equivalent is the AppConf type in config-gen.d.ts.
   */
  conf: AppConf;
}
/**
 * SearchBlockRequest is the request body for POST /api/search/searchBlock.
 */
export interface SearchBlockRequest {
  query: string; // Search query
  method: number /* int */; // 0=keyword, 1=query syntax, 2=SQL, 3=regex
  types?: SearchBlockTypes; // Block types filter
  page?: number /* int */; // Page number (default 1)
  pageSize?: number /* int */; // Page size (default 32)
  reqId?: number /* int64 */; // Request ID for deduplication
}
/**
 * FullTextSearchBlockRequest is the request body for POST /api/search/fullTextSearchBlock.
 */
export interface FullTextSearchBlockRequest {
  query: string; // Search query
  method: number /* int */; // 0=keyword, 1=query syntax, 2=regex, 3=SQL
  types?: SearchBlockTypes; // Block types filter
  paths?: string[]; // Limit search to these paths
  groupBy: number /* int */; // 0=no grouping, 1=group by document
  orderBy: number /* int */; // 0=relevance, 1=updated desc, 2=created desc, 3=rank desc, 4=rank asc, 5=updated asc, 6=created asc
  page?: number /* int */; // Page number (default 1)
  pageSize?: number /* int */; // Page size (default 32)
  reqId?: number /* int64 */; // Request ID for deduplication
}
/**
 * SearchBlockTypes specifies which block types to include in search results.
 */
export interface SearchBlockTypes {
  document: boolean;
  heading: boolean;
  list: boolean;
  listItem: boolean;
  codeBlock: boolean;
  mathBlock: boolean;
  table: boolean;
  blockquote: boolean;
  superBlock: boolean;
  paragraph: boolean;
  htmlBlock: boolean;
  embedBlock: boolean;
  databaseBlock: boolean;
  audioBlock: boolean;
  videoBlock: boolean;
  iframeBlock: boolean;
  widgetBlock: boolean;
  callout: boolean;
}
/**
 * FullTextSearchBlockResponse is the data field in the response from /api/search/fullTextSearchBlock.
 */
export interface FullTextSearchBlockResponse {
  blocks: (ResBlock | undefined)[];
  matchedBlockCount: number /* int */;
  matchedRootCount: number /* int */;
  pageCount: number /* int */;
  docMode: boolean;
}

