// Code generated by tygo. DO NOT EDIT.
// Re-generate with: cd app && pnpm gen:api-types
//
// This file contains TypeScript types for SiYuan application configuration,
// generated from kernel/conf/ and kernel/model/conf.go.


//////////
// source: statusbar.go

/**
 * StatusBar 底部状态栏配置。https://github.com/siyuan-note/siyuan/issues/16236
 */
export interface StatusBar {
  msgTaskDatabaseIndexCommitDisabled: boolean;
  msgTaskHistoryDatabaseIndexCommitDisabled: boolean;
  msgTaskAssetDatabaseIndexCommitDisabled: boolean;
  msgTaskHistoryGenerateFileDisabled: boolean;
}


//////////
// source: account.go

export interface Account {
  displayTitle: boolean;
  displayVIP: boolean;
}

//////////
// source: ai.go

export interface AI {
  openAI?: OpenAI;
}
export interface OpenAI {
  apiKey: string;
  apiTimeout: number /* int */;
  apiProxy: string;
  apiModel: string;
  apiMaxTokens: number /* int */;
  apiTemperature: number /* float64 */;
  apiMaxContexts: number /* int */;
  apiBaseURL: string;
  apiUserAgent: string;
  apiProvider: string; // OpenAI, Azure
  apiVersion: string; // Azure API version
}

//////////
// source: api.go

export interface API {
  token: string;
}

//////////
// source: appearance.go

export interface Appearance {
  mode: number /* int */; // 模式：0：明亮，1：暗黑
  modeOS: boolean; // 模式是否跟随系统
  darkThemes: (AppearanceTheme | undefined)[]; // 暗黑模式外观主题列表
  lightThemes: (AppearanceTheme | undefined)[]; // 明亮模式外观主题列表
  themeDark: string; // 选择的暗黑模式外观主题
  themeLight: string; // 选择的明亮模式外观主题
  themeVer: string; // 选择的主题版本
  icons: string[]; // 图标列表
  icon: string; // 选择的图标
  iconVer: string; // 选择的图标版本
  codeBlockThemeLight: string; // 明亮模式下代码块主题
  codeBlockThemeDark: string; // 暗黑模式下代码块主题
  lang: string; // 选择的界面语言，同 AppConf.Lang
  themeJS: boolean; // 是否启用了主题 JavaScript
  closeButtonBehavior: number /* int */; // 关闭按钮行为，0：退出，1：最小化到托盘
  hideStatusBar: boolean; // 是否隐藏底部状态栏
  statusBar?: StatusBar; // 底部状态栏配置
}
export interface AppearanceTheme {
  name: string; // daylight
  label: string; // i18n display name
}

//////////
// source: bazaar.go

export interface Bazaar {
  trust: boolean;
  petalDisabled: boolean;
}

//////////
// source: editor.go

export interface Editor {
  allowSVGScript: boolean; // 允许执行 SVG 内脚本
  allowHTMLBLockScript: boolean; // 允许执行 HTML 块内脚本
  fontSize: number /* int */; // 字体大小
  fontSizeScrollZoom: boolean; // 字体大小是否支持滚轮缩放
  fontFamily: string; // 字体
  codeSyntaxHighlightLineNum: boolean; // 代码块是否显示行号
  codeTabSpaces: number /* int */; // 代码块中 Tab 转换空格数，配置为 0 则表示不转换
  codeLineWrap: boolean; // 代码块是否自动折行
  codeLigatures: boolean; // 代码块是否连字
  displayBookmarkIcon: boolean; // 是否显示内容块角标
  displayNetImgMark: boolean; // 是否显示网络图片角标
  generateHistoryInterval: number /* int */; // 生成历史时间间隔，单位：分钟
  historyRetentionDays: number /* int */; // 历史保留天数
  emoji: string[]; // 常用表情
  virtualBlockRef: boolean; // 是否启用虚拟引用
  virtualBlockRefExclude: string; // 虚拟引用关键字排除列表
  virtualBlockRefInclude: string; // 虚拟引用关键字包含列表
  blockRefDynamicAnchorTextMaxLen: number /* int */; // 块引动态锚文本最大长度
  plantUMLServePath: string; // PlantUML 伺服地址
  fullWidth: boolean; // 是否使用最大宽度
  katexMacros: string; // KeTex 宏定义
  readOnly: boolean; // 只读模式
  embedBlockBreadcrumb: boolean; // 嵌入块是否显示面包屑
  listLogicalOutdent: boolean; // 列表逻辑反向缩进
  listItemDotNumberClickFocus: boolean; // 单击列表项标记聚焦
  floatWindowMode: number /* int */; // 浮窗触发模式，0：光标悬停，1：按住 Ctrl 悬停，2：不触发浮窗
  dynamicLoadBlocks: number /* int */; // 块动态数，可配置区间 [48, 1024]
  justify: boolean; // 是否两端对齐
  rtl: boolean; // 是否从右到左显示
  spellcheck: boolean; // 是否启用拼写检查
  spellcheckLanguages: string[]; // 拼写检查语言
  onlySearchForDoc: boolean; // 是否启用 [[ 仅搜索文档块
  backlinkExpandCount: number /* int */; // 反向链接默认展开数量
  backmentionExpandCount: number /* int */; // 反链提及默认展开数量
  backlinkContainChildren: boolean; // 反向链接是否包含子块进行计算
  backlinkSort?: number /* int */; // 反向链接排序方式
  backmentionSort?: number /* int */; // 反链提及排序方式
  headingEmbedMode: number /* int */; // 标题嵌入块模式，0：显示标题与下方的块，1：仅显示标题，2：仅显示标题下方的块
  markdown?: any; // Markdown 配置
}
export const MinDynamicLoadBlocks = 48;

//////////
// source: export.go

export interface Export {
  paragraphBeginningSpace: boolean; // 是否使用中文排版段落开头空两格
  addTitle: boolean; // 是否添加标题
  /**
   * 内容块引用导出模式
   *   2：锚文本块链
   *   3：仅锚文本
   *   4：块引转脚注+锚点哈希
   *  （5：锚点哈希 https://github.com/siyuan-note/siyuan/issues/10265 已经废弃 https://github.com/siyuan-note/siyuan/issues/13331）
   *  （0：使用原始文本，1：使用 Blockquote，都已经废弃 https://github.com/siyuan-note/siyuan/issues/3155）
   */
  blockRefMode: number /* int */;
  blockEmbedMode: number /* int */; // 内容块引用导出模式，0：使用原始文本，1：使用 Blockquote
  blockRefTextLeft: string; // 内容块引用导出锚文本左侧符号，默认留空
  blockRefTextRight: string; // 内容块引用导出锚文本右侧符号，默认留空
  tagOpenMarker: string; // 标签开始标记符，默认是 #
  tagCloseMarker: string; // 标签结束标记符，默认是 #
  fileAnnotationRefMode: number /* int */; // 文件标注引用导出模式，0：文件名 - 页码 - 锚文本，1：仅锚文本
  pandocBin: string; // Pandoc 可执行文件路径
  pandocParams: string; // Pandoc 额外参数
  docxTemplate: string; // Docx 导出时模板文件路径 TODO 已经废弃，计划于 2026 年 6 月 30 日后删除 https://github.com/siyuan-note/siyuan/issues/16845
  removeAssetsID: boolean; // Markdown 导出时是否移除资源文件名 ID 部分 https://github.com/siyuan-note/siyuan/issues/16065
  markdownYFM: boolean; // Markdown 导出时是否添加 YAML Front Matter https://github.com/siyuan-note/siyuan/issues/7727
  inlineMemo: boolean; // 是否导出行级备注 https://github.com/siyuan-note/siyuan/issues/14605
  includeSubDocs: boolean; // 是否导出子文档 https://github.com/siyuan-note/siyuan/issues/13635
  includeRelatedDocs: boolean; // 是否导出关联文档 https://github.com/siyuan-note/siyuan/issues/13635
  pdfFooter: string; // PDF 导出时页脚内容
  pdfWatermarkStr: string; // PDF 导出时水印文本或水印文件路径
  pdfWatermarkDesc: string; // PDF 导出时水印位置、大小和样式等
  imageWatermarkStr: string; // 图片导出时水印文本或水印文件路径
  imageWatermarkDesc: string; // 图片导出时水印位置、大小和样式等
}

//////////
// source: filetree.go

export interface FileTree {
  alwaysSelectOpenedFile: boolean; // 是否自动选中当前打开的文件
  openFilesUseCurrentTab: boolean; // 在当前页签打开文件
  refCreateSaveBox: string; // 块引时新建文档存储笔记本
  refCreateSavePath: string; // 块引时新建文档存储路径
  docCreateSaveBox: string; // 新建文档存储笔记本
  docCreateSavePath: string; // 新建文档存储路径
  maxListCount: number /* int */; // 最大列出数量
  maxOpenTabCount: number /* int */; // 最大打开页签数量
  allowCreateDeeper: boolean; // 允许创建超过 7 层深度的子文档
  removeDocWithoutConfirm: boolean; // 删除文档时是否不需要确认
  closeTabsOnStart: boolean; // 启动时关闭所有页签
  useSingleLineSave: boolean; // 使用单行保存文档 .sy 和属性视图 .json
  largeFileWarningSize: number /* int */; // 大文件警告大小（单位：MB）
  createDocAtTop?: boolean; // 在顶部创建新文档 https://github.com/siyuan-note/siyuan/issues/16327
  sort: number /* int */; // 排序方式
  recentDocsMaxListCount: number /* int */; // 最近的文档最大列出数量
  noSplitScreenWhenOpenTab: boolean; // 打开页签时不分屏 https://github.com/siyuan-note/siyuan/issues/16833
}
export const MinFileTreeRecentDocsListCount = 32;
export const MaxFileTreeRecentDocsListCount = 256;

//////////
// source: flashcard.go

export interface Flashcard {
  newCardLimit: number /* int */; // 新卡上限 https://github.com/siyuan-note/siyuan/issues/7695
  reviewCardLimit: number /* int */; // 复习卡上限 https://github.com/siyuan-note/siyuan/issues/7703
  mark: boolean; // 是否启用标记制卡 https://github.com/siyuan-note/siyuan/issues/7794
  list: boolean; // 是否启用列表块制卡 https://github.com/siyuan-note/siyuan/issues/7701
  superBlock: boolean; // 是否启用超级块制卡 https://github.com/siyuan-note/siyuan/issues/7702
  heading: boolean; // 是否启用标题块制卡 https://github.com/siyuan-note/siyuan/issues/9005
  deck: boolean; // 是否启用卡包制卡 https://github.com/siyuan-note/siyuan/issues/7724
  reviewMode: number /* int */; // 复习模式，0：新旧混合，1：新卡优先，2：旧卡优先 https://github.com/siyuan-note/siyuan/issues/10303
  /**
   * Apply result optimized by FSRS optimizer https://github.com/siyuan-note/siyuan/issues/9309
   */
  requestRetention: number /* float64 */;
  maximumInterval: number /* int */;
  weights: string;
}

//////////
// source: graph.go

export interface Graph {
  maxBlocks: number /* int */; // 内容块最大显示数
  local?: LocalGraph; // 局部图
  global?: GlobalGraph; // 全局图
}
export interface LocalGraph {
  dailyNote: boolean;
  type?: TypeFilter;
  d3?: D3;
}
export interface GlobalGraph {
  minRefs: number /* int */; // 引用次数
  dailyNote: boolean;
  type?: TypeFilter;
  d3?: D3;
}
export interface TypeFilter {
  tag: boolean;
  paragraph: boolean;
  heading: boolean;
  math: boolean;
  code: boolean;
  table: boolean;
  list: boolean;
  listItem: boolean;
  blockquote: boolean;
  super: boolean;
  callout: boolean;
}
export interface D3 {
  nodeSize: number /* float64 */;
  linkWidth: number /* float64 */;
  lineOpacity: number /* float64 */;
  centerStrength: number /* float64 */;
  collideRadius: number /* float64 */;
  collideStrength: number /* float64 */;
  linkDistance: number /* int */;
  arrow: boolean;
}

//////////
// source: lang.go

export interface Lang {
  label: string; // 简体中文
  name: string; // zh_CN
}

//////////
// source: layout.go

export type UILayout = { [key: string]: any}; // 界面布局
export type Keymap = { [key: string]: any}; // 快捷键

//////////
// source: publish.go

export interface Publish {
  enable: boolean; // 是否启用发布服务
  port: number /* uint16 */; // 发布服务端口
  auth?: BasicAuth; // Basic 认证
}
export interface BasicAuth {
  enable: boolean; // 是否启用基础认证
  accounts: (BasicAuthAccount | undefined)[]; // 账户列表
}
export interface BasicAuthAccount {
  username: string; // 用户名
  password: string; // 密码
  memo: string; // 备注
}

//////////
// source: repo.go

export interface Repo {
  key: string /* []byte */; // AES 密钥
  /**
   * 同步索引计时，单位毫秒，超过该时间则提示用户索引性能下降
   * If the data repo indexing time is greater than 12s, prompt user to purge the data repo https://github.com/siyuan-note/siyuan/issues/9613
   * Supports configuring data sync index time-consuming prompts https://github.com/siyuan-note/siyuan/issues/9698
   */
  syncIndexTiming: number /* int64 */;
  /**
   * 自动清理数据仓库 Automatic purge for local data repo https://github.com/siyuan-note/siyuan/issues/13091
   */
  indexRetentionDays: number /* int */; // 索引保留天数
  retentionIndexesDaily: number /* int */; // 每日保留索引数
}

//////////
// source: search.go

export interface Search {
  document: boolean;
  heading: boolean;
  list: boolean;
  listItem: boolean;
  codeBlock: boolean;
  mathBlock: boolean;
  table: boolean;
  blockquote: boolean;
  superBlock: boolean;
  paragraph: boolean;
  htmlBlock: boolean;
  embedBlock: boolean;
  databaseBlock: boolean;
  audioBlock: boolean;
  videoBlock: boolean;
  iframeBlock: boolean;
  widgetBlock: boolean;
  callout: boolean;
  limit: number /* int */;
  caseSensitive: boolean;
  name: boolean;
  alias: boolean;
  memo: boolean;
  ial: boolean;
  indexAssetPath: boolean;
  backlinkMentionName: boolean;
  backlinkMentionAlias: boolean;
  backlinkMentionAnchor: boolean;
  backlinkMentionDoc: boolean;
  backlinkMentionKeywordsLimit: number /* int */;
  virtualRefName: boolean;
  virtualRefAlias: boolean;
  virtualRefAnchor: boolean;
  virtualRefDoc: boolean;
}

//////////
// source: snippet.go

export interface Snpt {
  enabledCSS: boolean;
  enabledJS: boolean;
}
export interface Snippet {
  id: string;
  name: string;
  type: string; // js/css
  enabled: boolean;
  disabledInPublish: boolean;
  content: string;
}

//////////
// source: stat.go

export interface Stat {
  treeCount: number /* int */;
  cTreeCount: number /* int */;
  blockCount: number /* int */;
  cBlockCount: number /* int */;
  dataSize: number /* int64 */;
  cDataSize: number /* int64 */;
  assetsSize: number /* int64 */;
  cAssetsSize: number /* int64 */;
}

//////////
// source: sync.go

export interface Sync {
  cloudName: string; // 云端同步目录名称
  enabled: boolean; // 是否开启同步
  perception: boolean; // 是否开启感知
  mode: number /* int */; // 同步模式，0：未设置（为兼容已有配置，initConf 函数中会转换为 1），1：自动，2：手动 https://github.com/siyuan-note/siyuan/issues/5089，3：完全手动 https://github.com/siyuan-note/siyuan/issues/7295
  interval: number /* int */; // 自动同步间隔，单位：秒
  synced: number /* int64 */; // 最近同步时间
  stat: string; // 最近同步统计信息
  generateConflictDoc: boolean; // 云端同步冲突时是否生成冲突文档
  provider: number /* int */; // 云端存储服务提供者
  s3?: S3; // S3 对象存储服务配置
  webdav?: WebDAV; // WebDAV 服务配置
  local?: Local; // 本地文件系统 服务配置
}
export interface S3 {
  endpoint: string; // 服务端点
  accessKey: string; // Access Key
  secretKey: string; // Secret Key
  bucket: string; // 存储空间
  region: string; // 存储区域
  pathStyle: boolean; // 是否使用路径风格
  skipTlsVerify: boolean; // 是否跳过 TLS 验证
  timeout: number /* int */; // 超时时间，单位：秒
  concurrentReqs: number /* int */; // 并发请求数
}
export interface WebDAV {
  endpoint: string; // 服务端点
  username: string; // 用户名
  password: string; // 密码
  skipTlsVerify: boolean; // 是否跳过 TLS 验证
  timeout: number /* int */; // 超时时间，单位：秒
  concurrentReqs: number /* int */; // 并发请求数
}
export interface Local {
  endpoint: string; // 服务端点 (本地文件系统目录)
  timeout: number /* int */; // 超时时间，单位：秒
  concurrentReqs: number /* int */; // 并发请求数
}
export const ProviderSiYuan = 0; // ProviderSiYuan 为思源官方提供的云端存储服务
export const ProviderS3 = 2; // ProviderS3 为 S3 协议对象存储提供的云端存储服务
export const ProviderWebDAV = 3; // ProviderWebDAV 为 WebDAV 协议提供的云端存储服务
export const ProviderLocal = 4; // ProviderLocal 为本地文件系统提供的存储服务

//////////
// source: system.go

export interface System {
  id: string;
  name: string;
  kernelVersion: string;
  os: string;
  osPlatform: string;
  container: string; // docker, android, ios, harmony, std
  isMicrosoftStore: boolean;
  isInsider: boolean;
  homeDir: string;
  workspaceDir: string;
  appDir: string;
  confDir: string;
  dataDir: string;
  networkServe: boolean; // 是否开启网络伺服
  networkServeTLS: boolean; // 是否开启 HTTPS 网络伺服
  networkProxy?: NetworkProxy;
  downloadInstallPkg: boolean;
  autoLaunch2: number /* int */; // 0：不自动启动，1：自动启动，2：自动启动+隐藏主窗口
  lockScreenMode: number /* int */; // 0：手动，1：手动+跟随系统 https://github.com/siyuan-note/siyuan/issues/9087
  disabledFeatures: string[];
  microsoftDefenderExcluded: boolean; // 是否已加入 Microsoft Defender 排除项 https://github.com/siyuan-note/siyuan/issues/13650
}
export interface NetworkProxy {
  scheme: string;
  host: string;
  port: string;
}

//////////
// source: tag.go

export interface Tag {
  sort: number /* int */; // 排序方式
}

//////////
// source: user.go

export interface User {
  userId: string;
  userName: string;
  userAvatarURL: string;
  userHomeBImgURL: string;
  userTitles: (UserTitle | undefined)[];
  userIntro: string;
  userNickname: string;
  userCreateTime: string;
  userSiYuanProExpireTime: number /* float64 */;
  userToken: string;
  userTokenExpireTime: string;
  userSiYuanRepoSize: number /* float64 */;
  userSiYuanPointExchangeRepoSize: number /* float64 */;
  userSiYuanAssetSize: number /* float64 */;
  userTrafficUpload: number /* float64 */;
  userTrafficDownload: number /* float64 */;
  userTrafficAPIGet: number /* float64 */;
  userTrafficAPIPut: number /* float64 */;
  userTrafficTime: number /* float64 */;
  userSiYuanSubscriptionPlan: number /* float64 */; // -1：未订阅，0：标准订阅，1：教育订阅，2：试用
  userSiYuanSubscriptionStatus: number /* float64 */; // -1：未订阅，0：订阅可用，1：订阅封禁，2：订阅过期
  userSiYuanSubscriptionType: number /* float64 */; // 0 年付；1 终生；2 月付
  userSiYuanOneTimePayStatus: number /* float64 */; // 0 未付费；1 已付费
}
export interface UserTitle {
  name: string;
  desc: string;
  icon: string;
}


//////////
// source: conf.go

/**
 * AppConf 维护应用元数据，保存在 ~/.siyuan/conf.json。
 */
export interface AppConf {
  logLevel: string; // 日志级别：off, trace, debug, info, warn, error, fatal
  appearance?: Appearance; // 外观
  langs: (Lang | undefined)[]; // 界面语言列表
  lang: string; // 选择的界面语言，同 Appearance.Lang
  fileTree?: FileTree; // 文档面板
  tag?: Tag; // 标签面板
  editor?: Editor; // 编辑器配置
  export?: Export; // 导出配置
  graph?: Graph; // 关系图配置
  uiLayout?: UILayout; // 界面布局。不要直接使用，使用 GetUILayout() 和 SetUILayout() 方法
  userData: string; // 社区用户信息，对 User 加密存储
  account?: Account; // 帐号配置
  readonly: boolean; // 是否是以只读模式运行
  serverAddrs: string[]; // 本地服务器地址列表
  accessAuthCode: string; // 访问授权码
  system?: System; // 系统配置
  keymap?: Keymap; // 快捷键配置
  sync?: Sync; // 同步配置
  search?: Search; // 搜索配置
  flashcard?: Flashcard; // 闪卡配置
  ai?: AI; // 人工智能配置
  bazaar?: Bazaar; // 集市配置
  stat?: Stat; // 统计
  api?: API; // API
  repo?: Repo; // 数据仓库
  publish?: Publish; // 发布服务
  openHelp: boolean; // 启动后是否需要打开用户指南
  showChangelog: boolean; // 是否显示版本更新日志
  cloudRegion: number /* int */; // 云端区域，0：中国大陆，1：北美
  snippet?: Snpt; // 代码片段
  dataIndexState: number /* int */; // 数据索引状态，0：已索引，1：未索引
  cookieKey: string; // 用于加密 Cookie 的密钥
}
export const MaskedUserData = "";
export const MaskedAccessAuthCode = "*******";

