#!/usr/bin/env node
// Helper script that combines tygo-generated TypeScript partial files
// into the final generated declaration files.
//
// Outputs:
//   api-gen.d.ts    - API endpoint request/response types (from kernel/api/types.go)
//   config-gen.d.ts - Application configuration types (from kernel/conf/ and kernel/model/conf.go)

const fs = require("fs");
const path = require("path");

const typesDir = path.resolve(__dirname, "../app/src/types");

/**
 * Combines multiple tygo partial files into a single output file.
 * @param {string[]} partials - Array of partial file names (relative to typesDir)
 * @param {string} outputName - Output file name (relative to typesDir)
 * @param {string} header     - Header text to prepend to the combined file
 */
function combinePartials(partials, outputName, header) {
    let combined = header + "\n";

    for (const partial of partials) {
        const filePath = path.join(typesDir, partial);
        if (fs.existsSync(filePath)) {
            let content = fs.readFileSync(filePath, "utf8");
            // Remove the auto-added "Code generated by tygo" header from each partial
            content = content.replace(/^\/\/ Code generated by tygo\. DO NOT EDIT\.\n/gm, "");
            combined += content + "\n";
            fs.unlinkSync(filePath);
        }
    }

    const outputPath = path.join(typesDir, outputName);
    fs.writeFileSync(outputPath, combined, "utf8");
    console.log(`Generated ${outputPath}`);
}

// 1. API endpoint request/response types
combinePartials(
    [".gen-api.ts"],
    "api-gen.d.ts",
    `// Code generated by tygo. DO NOT EDIT.
// Re-generate with: cd app && pnpm gen:api-types
//
// This file contains TypeScript types for SiYuan public API endpoint
// request/response parameters, generated from kernel/api/types.go.
`,
);

// 2. Application configuration types
combinePartials(
    [".gen-conf-util.ts", ".gen-conf-conf.ts", ".gen-conf-model.ts"],
    "config-gen.d.ts",
    `// Code generated by tygo. DO NOT EDIT.
// Re-generate with: cd app && pnpm gen:api-types
//
// This file contains TypeScript types for SiYuan application configuration,
// generated from kernel/conf/ and kernel/model/conf.go.
`,
);

