#!/usr/bin/env node
// Helper script that combines tygo-generated TypeScript partial files
// into the final config-gen.d.ts declaration file.

const fs = require("fs");
const path = require("path");

const typesDir = path.resolve(__dirname, "../app/src/types");

const partials = [
    ".config-gen-util.ts",
    ".config-gen-conf.ts",
    ".config-gen-model.ts",
];

const header = `// Code generated by tygo. DO NOT EDIT.
// Re-generate with: cd app && pnpm gen:conf
`;

let combined = header + "\n";

for (const partial of partials) {
    const filePath = path.join(typesDir, partial);
    if (fs.existsSync(filePath)) {
        let content = fs.readFileSync(filePath, "utf8");
        // Remove the auto-added "Code generated by tygo" header from intermediate files
        content = content.replace(/^\/\/ Code generated by tygo\. DO NOT EDIT\.\n/gm, "");
        combined += content + "\n";
        fs.unlinkSync(filePath);
    }
}

const outputPath = path.join(typesDir, "config-gen.d.ts");
fs.writeFileSync(outputPath, combined, "utf8");
console.log(`Generated ${outputPath}`);
