// SiYuan - Refactor your thinking
// Copyright (c) 2020-present, b3log.org
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Package api defines typed request and response structures for SiYuan public API
// endpoints. These types serve as the single source of truth for API contracts
// between the backend and the frontend.
//
// TypeScript equivalents are auto-generated by tygo — run `cd app && pnpm gen:api-types`
// after modifying any struct here.
package api

// ---- Notebook API (/api/notebook/) ----

// LsNotebooksRequest is the request body for POST /api/notebook/lsNotebooks.
type LsNotebooksRequest struct {
	// Whether to include flashcard counts for each notebook (default false).
	Flashcard bool `json:"flashcard"`
}

// LsNotebooksResponse is the data field in the response from /api/notebook/lsNotebooks.
type LsNotebooksResponse struct {
	Notebooks []*ResNotebook `json:"notebooks"`
}

// ResNotebook represents a notebook in API responses.
type ResNotebook struct {
	ID                string `json:"id"`
	Name              string `json:"name"`
	Icon              string `json:"icon"`
	Sort              int    `json:"sort"`
	SortMode          int    `json:"sortMode"`
	Closed            bool   `json:"closed"`
	NewFlashcardCount int    `json:"newFlashcardCount"`
	DueFlashcardCount int    `json:"dueFlashcardCount"`
	FlashcardCount    int    `json:"flashcardCount"`
}

// OpenNotebookRequest is the request body for POST /api/notebook/openNotebook.
type OpenNotebookRequest struct {
	Notebook string `json:"notebook"` // Notebook ID
}

// CloseNotebookRequest is the request body for POST /api/notebook/closeNotebook.
type CloseNotebookRequest struct {
	Notebook string `json:"notebook"` // Notebook ID
}

// RenameNotebookRequest is the request body for POST /api/notebook/renameNotebook.
type RenameNotebookRequest struct {
	Notebook string `json:"notebook"` // Notebook ID
	Name     string `json:"name"`     // New notebook name
}

// CreateNotebookRequest is the request body for POST /api/notebook/createNotebook.
type CreateNotebookRequest struct {
	Name string `json:"name"` // New notebook name
}

// CreateNotebookResponse is the data field in the response from /api/notebook/createNotebook.
type CreateNotebookResponse struct {
	Notebook *ResNotebook `json:"notebook"`
}

// RemoveNotebookRequest is the request body for POST /api/notebook/removeNotebook.
type RemoveNotebookRequest struct {
	Notebook string `json:"notebook"` // Notebook ID
}

// GetNotebookConfRequest is the request body for POST /api/notebook/getNotebookConf.
type GetNotebookConfRequest struct {
	Notebook string `json:"notebook"` // Notebook ID
}

// SetNotebookConfRequest is the request body for POST /api/notebook/setNotebookConf.
type SetNotebookConfRequest struct {
	Notebook string              `json:"notebook"` // Notebook ID
	Conf     ResNotebookConfData `json:"conf"`
}

// ResNotebookConfData represents notebook configuration.
type ResNotebookConfData struct {
	Name          string `json:"name"`
	Icon          string `json:"icon"`
	Sort          int    `json:"sort"`
	SortMode      int    `json:"sortMode"`
	RefCreateSaveBox  string `json:"refCreateSaveBox"`
	RefCreateSavePath string `json:"refCreateSavePath"`
	DocCreateSaveBox  string `json:"docCreateSaveBox"`
	DocCreateSavePath string `json:"docCreateSavePath"`
	DailyNoteSavePath string `json:"dailyNoteSavePath"`
	DailyNoteTemplatePath string `json:"dailyNoteTemplatePath"`
}

// ---- Document API (/api/filetree/) ----

// CreateDocWithMdRequest is the request body for POST /api/filetree/createDocWithMd.
type CreateDocWithMdRequest struct {
	Notebook string `json:"notebook"`         // Target notebook ID
	Path     string `json:"path"`             // Document path (e.g. /path/to/doc)
	Markdown string `json:"markdown"`         // Markdown content
	Attrs    map[string]string `json:"attrs,omitempty"` // Optional block attributes
}

// RenameDocRequest is the request body for POST /api/filetree/renameDoc.
type RenameDocRequest struct {
	Notebook string `json:"notebook"` // Notebook ID
	Path     string `json:"path"`     // Document path
	Title    string `json:"title"`    // New title
}

// RemoveDocRequest is the request body for POST /api/filetree/removeDoc.
type RemoveDocRequest struct {
	Notebook string `json:"notebook"` // Notebook ID
	Path     string `json:"path"`     // Document path
}

// MoveDocsRequest is the request body for POST /api/filetree/moveDocs.
type MoveDocsRequest struct {
	FromNotebook string   `json:"fromNotebook"` // Source notebook ID
	FromPaths    []string `json:"fromPaths"`    // Source document paths
	ToNotebook   string   `json:"toNotebook"`   // Target notebook ID
	ToPath       string   `json:"toPath"`       // Target parent path
}

// GetHPathByPathRequest is the request body for POST /api/filetree/getHPathByPath.
type GetHPathByPathRequest struct {
	Notebook string `json:"notebook"` // Notebook ID
	Path     string `json:"path"`     // Document path
}

// GetHPathByIDRequest is the request body for POST /api/filetree/getHPathByID.
type GetHPathByIDRequest struct {
	ID string `json:"id"` // Block ID
}

// GetPathByIDRequest is the request body for POST /api/filetree/getPathByID.
type GetPathByIDRequest struct {
	ID string `json:"id"` // Block ID
}

// GetIDsByHPathRequest is the request body for POST /api/filetree/getIDsByHPath.
type GetIDsByHPathRequest struct {
	Notebook string `json:"notebook"` // Notebook ID
	Path     string `json:"path"`     // Human-readable path
}

// ---- Block API (/api/block/) ----

// TDataType is the type of block data content: Markdown or DOM.
type TDataType = string // "markdown" | "dom"

// InsertBlockRequest is the request body for POST /api/block/insertBlock.
type InsertBlockRequest struct {
	DataType   TDataType `json:"dataType"`             // Content type: "markdown" or "dom"
	Data       string    `json:"data"`                 // Content to insert
	NextID     string    `json:"nextID,omitempty"`     // ID of the block to insert before
	PreviousID string    `json:"previousID,omitempty"` // ID of the block to insert after
	ParentID   string    `json:"parentID,omitempty"`   // ID of the parent block
}

// PrependBlockRequest is the request body for POST /api/block/prependBlock.
type PrependBlockRequest struct {
	DataType TDataType `json:"dataType"` // Content type: "markdown" or "dom"
	Data     string    `json:"data"`     // Content to prepend
	ParentID string    `json:"parentID"` // ID of the parent block
}

// AppendBlockRequest is the request body for POST /api/block/appendBlock.
type AppendBlockRequest struct {
	DataType TDataType `json:"dataType"` // Content type: "markdown" or "dom"
	Data     string    `json:"data"`     // Content to append
	ParentID string    `json:"parentID"` // ID of the parent block
}

// UpdateBlockRequest is the request body for POST /api/block/updateBlock.
type UpdateBlockRequest struct {
	ID       string    `json:"id"`       // Block ID
	DataType TDataType `json:"dataType"` // Content type: "markdown" or "dom"
	Data     string    `json:"data"`     // New content
}

// DeleteBlockRequest is the request body for POST /api/block/deleteBlock.
type DeleteBlockRequest struct {
	ID string `json:"id"` // Block ID
}

// MoveBlockRequest is the request body for POST /api/block/moveBlock.
type MoveBlockRequest struct {
	ID         string `json:"id"`                   // Block ID to move
	PreviousID string `json:"previousID,omitempty"` // ID of the block to place after
	ParentID   string `json:"parentID,omitempty"`   // ID of the parent block to place in
}

// FoldBlockRequest is the request body for POST /api/block/foldBlock.
type FoldBlockRequest struct {
	ID string `json:"id"` // Block ID
}

// UnfoldBlockRequest is the request body for POST /api/block/unfoldBlock.
type UnfoldBlockRequest struct {
	ID string `json:"id"` // Block ID
}

// GetBlockKramdownRequest is the request body for POST /api/block/getBlockKramdown.
type GetBlockKramdownRequest struct {
	ID string `json:"id"` // Block ID
}

// GetBlockKramdownResponse is the data field in the response from /api/block/getBlockKramdown.
type GetBlockKramdownResponse struct {
	ID       string `json:"id"`
	Kramdown string `json:"kramdown"`
}

// GetChildBlocksRequest is the request body for POST /api/block/getChildBlocks.
type GetChildBlocksRequest struct {
	ID string `json:"id"` // Block ID
}

// TransferBlockRefRequest is the request body for POST /api/block/transferBlockRef.
type TransferBlockRefRequest struct {
	FromID string `json:"fromID"` // Source block ID
	ToID   string `json:"toID"`   // Target block ID
}

// GetBlockRequest is the request body for POST /api/block/getBlock.
type GetBlockRequest struct {
	ID string `json:"id"` // Block ID
}

// ResBlock represents a block returned in API responses.
type ResBlock struct {
	Box      string            `json:"box"`
	Path     string            `json:"path"`
	HPath    string            `json:"hPath"`
	ID       string            `json:"id"`
	RootID   string            `json:"rootID"`
	ParentID string            `json:"parentID"`
	Name     string            `json:"name"`
	Alias    string            `json:"alias"`
	Memo     string            `json:"memo"`
	Tag      string            `json:"tag"`
	Content  string            `json:"content"`
	FContent string            `json:"fcontent"`
	Markdown string            `json:"markdown"`
	Folded   bool              `json:"folded"`
	Type     string            `json:"type"`
	SubType  string            `json:"subType"`
	IAL      map[string]string `json:"ial"`
	Children []*ResBlock       `json:"children"`
	RefCount int               `json:"refCount"`
	Sort     int               `json:"sort"`
	Created  string            `json:"created"`
	Updated  string            `json:"updated"`
}

// ResChildBlock represents a child block returned by /api/block/getChildBlocks.
type ResChildBlock struct {
	ID       string `json:"id"`
	Type     string `json:"type"`
	SubType  string `json:"subType,omitempty"`
	Content  string `json:"content,omitempty"`
	Markdown string `json:"markdown,omitempty"`
}

// ResOperation represents a transaction operation in API responses.
type ResOperation struct {
	Action     string      `json:"action"`
	Data       interface{} `json:"data"`
	ID         string      `json:"id"`
	ParentID   string      `json:"parentID"`
	PreviousID string      `json:"previousID"`
	NextID     string      `json:"nextID"`
	RetData    interface{} `json:"retData"`
}

// ResTransaction represents a transaction returned by block write operations.
type ResTransaction struct {
	DoOperations   []*ResOperation `json:"doOperations"`
	UndoOperations []*ResOperation `json:"undoOperations"`
}

// ---- Attribute API (/api/attr/) ----

// GetBlockAttrsRequest is the request body for POST /api/attr/getBlockAttrs.
type GetBlockAttrsRequest struct {
	ID string `json:"id"` // Block ID
}

// SetBlockAttrsRequest is the request body for POST /api/attr/setBlockAttrs.
type SetBlockAttrsRequest struct {
	ID    string            `json:"id"`    // Block ID
	Attrs map[string]string `json:"attrs"` // Attribute key-value pairs to set (set value to empty string to remove)
}

// ---- SQL API (/api/sql/) ----

// SQLRequest is the request body for POST /api/sql/sql.
type SQLRequest struct {
	Stmt string `json:"stmt"` // SQL SELECT statement
}

// ---- Template API (/api/template/) ----

// RenderTemplateRequest is the request body for POST /api/template/render.
type RenderTemplateRequest struct {
	ID   string `json:"id"`   // Block ID for template context
	Path string `json:"path"` // Template file path
}

// RenderSprigRequest is the request body for POST /api/template/renderSprig.
type RenderSprigRequest struct {
	Template string `json:"template"` // Sprig template string
}

// ---- File API (/api/file/) ----

// GetFileRequest is the request body for POST /api/file/getFile.
type GetFileRequest struct {
	Path string `json:"path"` // File path relative to the workspace data directory
}

// PutFileRequest is the request body for POST /api/file/putFile (multipart form).
type PutFileRequest struct {
	Path    string `json:"path"`    // File path relative to the workspace data directory
	IsDir   bool   `json:"isDir"`   // Whether to create a directory instead of a file
	ModTime int64  `json:"modTime"` // Modification time (Unix millisecond timestamp)
	// File content is provided as the "file" field in multipart form data
}

// RemoveFileRequest is the request body for POST /api/file/removeFile.
type RemoveFileRequest struct {
	Path string `json:"path"` // File path relative to the workspace data directory
}

// RenameFileRequest is the request body for POST /api/file/renameFile.
type RenameFileRequest struct {
	Path    string `json:"path"`    // Current file path
	NewPath string `json:"newPath"` // New file path
}

// ListFilesRequest is the request body for POST /api/file/listFiles.
type ListFilesRequest struct {
	Path string `json:"path"` // Directory path relative to the workspace data directory
}

// ResFile represents a file entry returned by /api/file/listFiles.
type ResFile struct {
	IsDir   bool   `json:"isDir"`
	IsSymlink bool `json:"isSymlink"`
	Name    string `json:"name"`
	Size    int64  `json:"size"`
	Updated int64  `json:"updated"` // Unix millisecond timestamp
}

// ---- Export API (/api/export/) ----

// ExportMdContentRequest is the request body for POST /api/export/exportMdContent.
type ExportMdContentRequest struct {
	ID string `json:"id"` // Document block ID
}

// ExportMdContentResponse is the data field in the response from /api/export/exportMdContent.
type ExportMdContentResponse struct {
	HPath   string `json:"hPath"`   // Human-readable path
	Content string `json:"content"` // Markdown content
}

// ---- Notification API (/api/notification/) ----

// PushMessageRequest is the request body for POST /api/notification/pushMsg.
type PushMessageRequest struct {
	Msg     string `json:"msg"`               // Message content
	Timeout int    `json:"timeout,omitempty"` // Display duration in milliseconds (default 7000)
}

// PushMessageResponse is the data field in the response from /api/notification/pushMsg.
type PushMessageResponse struct {
	ID string `json:"id"` // Message ID (can be used to close the message)
}

// PushErrMsgRequest is the request body for POST /api/notification/pushErrMsg.
type PushErrMsgRequest struct {
	Msg     string `json:"msg"`               // Error message content
	Timeout int    `json:"timeout,omitempty"` // Display duration in milliseconds (default 7000)
}

// PushErrMsgResponse is the data field in the response from /api/notification/pushErrMsg.
type PushErrMsgResponse struct {
	ID string `json:"id"` // Message ID
}

// ---- Network API (/api/network/) ----

// ForwardProxyRequest is the request body for POST /api/network/forwardProxy.
type ForwardProxyRequest struct {
	URL          string            `json:"url"`                    // Target URL
	Method       string            `json:"method"`                 // HTTP method
	Timeout      int               `json:"timeout,omitempty"`      // Timeout in milliseconds
	ContentType  string            `json:"contentType,omitempty"`  // Request content type
	Headers      []map[string]string `json:"headers,omitempty"`   // Request headers
	Payload      interface{}       `json:"payload,omitempty"`      // Request body
	PayloadEncoding string         `json:"payloadEncoding,omitempty"` // Payload encoding: "text", "base64", "base64-std", "base64-url", "base64-raw", "base64-url-raw"
	ResponseEncoding string        `json:"responseEncoding,omitempty"` // Response encoding: "text", "base64", "base64-std", "base64-url", "base64-raw", "base64-url-raw"
}

// ForwardProxyResponse is the data field in the response from /api/network/forwardProxy.
type ForwardProxyResponse struct {
	ContentType string `json:"contentType"` // Response content type
	Body        string `json:"body"`        // Response body (encoding determined by request's responseEncoding)
	BodyEncoding string `json:"bodyEncoding"` // Encoding used for body
	Headers     map[string][]string `json:"headers"` // Response headers
	Status      string `json:"status"`      // HTTP status text
	StatusCode  int    `json:"statusCode"`  // HTTP status code
}

// ---- System API (/api/system/) ----

// GetConfResponse is the data field in the response from /api/system/getConf.
// The conf field is defined in kernel/model/conf.go (AppConf).
type GetConfResponse struct {
	// conf contains the full application configuration.
	// The TypeScript equivalent is the AppConf type in config-gen.d.ts.
	Conf interface{} `json:"conf" tstype:"AppConf"`
}

// ---- Search API (/api/search/) ----

// SearchBlockRequest is the request body for POST /api/search/searchBlock.
type SearchBlockRequest struct {
	Query         string `json:"query"`         // Search query
	Method        int    `json:"method"`        // 0=keyword, 1=query syntax, 2=SQL, 3=regex
	Types         *SearchBlockTypes `json:"types,omitempty"` // Block types filter
	Page          int    `json:"page,omitempty"`        // Page number (default 1)
	PageSize      int    `json:"pageSize,omitempty"`    // Page size (default 32)
	ReqID         int64  `json:"reqId,omitempty"`       // Request ID for deduplication
}

// FullTextSearchBlockRequest is the request body for POST /api/search/fullTextSearchBlock.
type FullTextSearchBlockRequest struct {
	Query    string            `json:"query"`             // Search query
	Method   int               `json:"method"`            // 0=keyword, 1=query syntax, 2=regex, 3=SQL
	Types    *SearchBlockTypes `json:"types,omitempty"`   // Block types filter
	Paths    []string          `json:"paths,omitempty"`   // Limit search to these paths
	GroupBy  int               `json:"groupBy"`           // 0=no grouping, 1=group by document
	OrderBy  int               `json:"orderBy"`           // 0=relevance, 1=updated desc, 2=created desc, 3=rank desc, 4=rank asc, 5=updated asc, 6=created asc
	Page     int               `json:"page,omitempty"`    // Page number (default 1)
	PageSize int               `json:"pageSize,omitempty"` // Page size (default 32)
	ReqID    int64             `json:"reqId,omitempty"`    // Request ID for deduplication
}

// SearchBlockTypes specifies which block types to include in search results.
type SearchBlockTypes struct {
	Document      bool `json:"document"`
	Heading       bool `json:"heading"`
	List          bool `json:"list"`
	ListItem      bool `json:"listItem"`
	CodeBlock     bool `json:"codeBlock"`
	MathBlock     bool `json:"mathBlock"`
	Table         bool `json:"table"`
	Blockquote    bool `json:"blockquote"`
	SuperBlock    bool `json:"superBlock"`
	Paragraph     bool `json:"paragraph"`
	HtmlBlock     bool `json:"htmlBlock"`
	EmbedBlock    bool `json:"embedBlock"`
	DatabaseBlock bool `json:"databaseBlock"`
	AudioBlock    bool `json:"audioBlock"`
	VideoBlock    bool `json:"videoBlock"`
	IframeBlock   bool `json:"iframeBlock"`
	WidgetBlock   bool `json:"widgetBlock"`
	Callout       bool `json:"callout"`
}

// FullTextSearchBlockResponse is the data field in the response from /api/search/fullTextSearchBlock.
type FullTextSearchBlockResponse struct {
	Blocks            []*ResBlock `json:"blocks"`
	MatchedBlockCount int         `json:"matchedBlockCount"`
	MatchedRootCount  int         `json:"matchedRootCount"`
	PageCount         int         `json:"pageCount"`
	DocMode           bool        `json:"docMode"`
}
